sudo: required
services:
  - docker

before_install:
  - docker build -t ojepse/docker-react -f Dockerfile.dev .


script:
  - docker run ojepse/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-334352159172"
  bucket_type: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_SECRET_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

